(import (scheme base) (scheme file) (scheme write)
        (scheme process-context)
        (c0c driver))

(define (preprocess-source path)
  (let ((port (open-input-file path)))
    (let loop ((lines '()))
      (let ((line (read-line port)))
        (if (eof-object? line)
            (begin (close-input-port port)
                   (apply string-append (reverse lines)))
            (if (and (> (string-length line) 6)
                     (string=? (substring line 0 5) "#use ")
                     (char=? (string-ref line 5) #\"))
                (let* ((end (- (string-length line) 1))
                       (fp (substring line 6 end))
                       (inc (preprocess-source fp)))
                  (loop (cons (string-append inc "\n") lines)))
                (loop (cons (string-append line "\n") lines))))))))

(define libc (ffi-open #f))
(define c-system (ffi-fn libc "system" '(string) 'int))

(define (run-command cmd)
  (let ((rc (c-system cmd)))
    (unless (= rc 0)
      (error "c0c: command failed" cmd rc))))

(define (usage)
  (display "Usage: c0c <file.c0> [file2.c0 ...] [options]\n")
  (display "Options:\n")
  (display "  -o <file>        Output binary name (default: a.out)\n")
  (display "  --emit-c         Stop after C emission\n")
  (display "  --target <T>     Cross-compile target (e.g. x86_64-linux)\n")
  (display "  --runtime <dir>  Path to c0c runtime directory\n")
  (display "  --no-check       Disable contract assertions\n")
  (display "  -O0|-O1|-O2|-Oz  Optimization level (default: -O0)\n")
  (display "  -g               Include debug symbols\n")
  (display "  -S               Emit assembly instead of binary\n")
  (display "  --gc             Enable garbage collection (Boehm GC)\n")
  (newline)
  (exit 1))

(define (path-directory path)
  (let ((len (string-length path)))
    (let loop ((i (- len 1)))
      (cond
        ((< i 0) ".")
        ((char=? (string-ref path i) #\/) (substring path 0 i))
        (else (loop (- i 1)))))))

(define opt-level "0")
(define debug-mode #f)
(define emit-asm #f)
(define use-gc #f)

(define (parse-args args)
  (let loop ((args args) (sources '()) (output "a.out")
             (emit-c #f) (target #f) (runtime-dir #f) (no-check #f))
    (cond
      ((null? args)
       (when (null? sources) (usage))
       (values (reverse sources) output emit-c target runtime-dir no-check))
      ((string=? (car args) "-o")
       (when (null? (cdr args)) (usage))
       (loop (cddr args) sources (cadr args) emit-c target runtime-dir no-check))
      ((string=? (car args) "--emit-c")
       (loop (cdr args) sources output #t target runtime-dir no-check))
      ((string=? (car args) "--target")
       (when (null? (cdr args)) (usage))
       (loop (cddr args) sources output emit-c (cadr args) runtime-dir no-check))
      ((string=? (car args) "--runtime")
       (when (null? (cdr args)) (usage))
       (loop (cddr args) sources output emit-c target (cadr args) no-check))
      ((string=? (car args) "--no-check")
       (loop (cdr args) sources output emit-c target runtime-dir #t))
      ((string=? (car args) "-O0") (set! opt-level "0")
       (loop (cdr args) sources output emit-c target runtime-dir no-check))
      ((string=? (car args) "-O1") (set! opt-level "1")
       (loop (cdr args) sources output emit-c target runtime-dir no-check))
      ((string=? (car args) "-O2") (set! opt-level "2")
       (loop (cdr args) sources output emit-c target runtime-dir no-check))
      ((string=? (car args) "-Oz") (set! opt-level "z")
       (loop (cdr args) sources output emit-c target runtime-dir no-check))
      ((string=? (car args) "-g") (set! debug-mode #t)
       (loop (cdr args) sources output emit-c target runtime-dir no-check))
      ((string=? (car args) "-S") (set! emit-asm #t)
       (loop (cdr args) sources output emit-c target runtime-dir no-check))
      ((string=? (car args) "--gc") (set! use-gc #t)
       (loop (cdr args) sources output emit-c target runtime-dir no-check))
      ((or (string=? (car args) "-h") (string=? (car args) "--help"))
       (usage))
      (else
       (loop (cdr args) (cons (car args) sources) output emit-c target
             runtime-dir no-check)))))

(let ((args (cddr (command-line))))
  (when (null? args) (usage))
  (call-with-values
    (lambda () (parse-args args))
    (lambda (sources output emit-c target runtime-dir no-check)
      (let* ((rev (reverse sources))
             (first-source (car rev))
             (preprocessed
               (let loop ((fs rev) (acc ""))
                 (if (null? fs) acc
                     (loop (cdr fs) (string-append acc (preprocess-source (car fs)) "\n")))))
             (c-code (compile-c0-to-c first-source no-check preprocessed))
             (c-file (string-append output ".c")))
        (let ((out (open-output-file c-file)))
          (write-string c-code out)
          (close-output-port out))
        (if emit-c
            (begin (display "Wrote ") (display c-file) (newline))
            (let* ((script-dir (path-directory first-source))
                   (rt-dir (or runtime-dir
                               (string-append script-dir "/runtime")))
                   (out-file (if emit-asm
                                 (string-append output ".s")
                                 output))
                   (cmd (string-append
                          "zig cc -O" opt-level " -fwrapv -std=c11 "
                          (if debug-mode "-g " "")
                          (if emit-asm "-S " "")
                          (if (and (not debug-mode) (not (string=? opt-level "0")))
                              "-s " "")
                          (if use-gc "-DC0_USE_GC " "")
                          "-I" rt-dir " "
                          (if target
                              (string-append "-target " target " ")
                              "")
                          c-file " "
                          (if emit-asm "" (string-append rt-dir "/c0rt.c "))
                          (if (and use-gc (not emit-asm)) "-lgc " "")
                          "-o " out-file)))
              (run-command cmd)
              (delete-file c-file)
              (when emit-asm
                (display "Wrote ") (display out-file) (newline))))))))
